// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc812.BB9;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController robotDriveSubsystemSpeedController1;
    public static SpeedController robotDriveSubsystemSpeedController2;
    public static SpeedController robotDriveSubsystemSpeedController3;
    public static SpeedController robotDriveSubsystemSpeedController4;
    public static RobotDrive robotDriveSubsystemRobotDrive41;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        robotDriveSubsystemSpeedController1 = new Talon(1);
        LiveWindow.addActuator("Robot Drive Subsystem", "Speed Controller 1", (Talon) robotDriveSubsystemSpeedController1);
        
        robotDriveSubsystemSpeedController2 = new Talon(2);
        LiveWindow.addActuator("Robot Drive Subsystem", "Speed Controller 2", (Talon) robotDriveSubsystemSpeedController2);
        
        robotDriveSubsystemSpeedController3 = new Talon(3);
        LiveWindow.addActuator("Robot Drive Subsystem", "Speed Controller 3", (Talon) robotDriveSubsystemSpeedController3);
        
        robotDriveSubsystemSpeedController4 = new Talon(4);
        LiveWindow.addActuator("Robot Drive Subsystem", "Speed Controller 4", (Talon) robotDriveSubsystemSpeedController4);
        
        robotDriveSubsystemRobotDrive41 = new RobotDrive(robotDriveSubsystemSpeedController1, robotDriveSubsystemSpeedController2,
              robotDriveSubsystemSpeedController3, robotDriveSubsystemSpeedController4);
        
        robotDriveSubsystemRobotDrive41.setSafetyEnabled(true);
        robotDriveSubsystemRobotDrive41.setExpiration(0.1);
        robotDriveSubsystemRobotDrive41.setSensitivity(0.5);
        robotDriveSubsystemRobotDrive41.setMaxOutput(1.0);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
